server:
  port: 8300
spring:
  application:
    name: cms-auth
---
#redis连接
spring:
  redis:
    database: 1
    host: 118.25.227.125
    port: 6379
    password: z787242784
---
spring:
  datasource:

    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://118.25.227.125:3306/oauth2-users?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: z787242784
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
mybatis:
  mapper-locations: classpath*:mapper/*.xml

#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql

---
#生成实体类链接
datasource.driver-class-name: com.mysql.jdbc.Driver
datasource.url: jdbc:mysql://118.25.227.125:3306/oauth2-users?useUnicode=true&characterEncoding=utf8&useSSL=false
datasource.username: root
datasource.password: z787242784