eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false #是否将自己注册到eureka server中
    fetch-registry: false #表示是否从eureka server中获取注册信息
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8100/eureka/
